name: Lint

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  lint:
    runs-on: ubuntu-20.04
    env:
      TOXENV: "lint, newsfragment"

    steps:
    - uses: actions/checkout@v2
      with:
        # Need history on all branches for newsfragment to work.
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip tox
        tox --notest

    - name: Runner info
      uses: twisted/python-info-action@v1

    - name: Tox lint info
      uses: twisted/python-info-action@v1
      with:
        python-path: .tox/lint/*/python

    - name: Tox newsfragment info
      uses: twisted/python-info-action@v1
      with:
        python-path: .tox/newsfragment/*/python

    - name: Lint
      run: |
        python --version
        tox -q
