name: Release Twisted

on:
  release:
    types: [ created ]

jobs:
  build-src-dist:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-20.04]
          python-version: [3.8]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: ./.github/actions/display-python-info

    - name: Get pip cache dir
      id: pip-cache
      run: |
        python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"

    - uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
            ${{ runner.os }}-pip-

    - name: Build src dist
      run: |
        python setup.py sdist --formats=gztar -d dist

    - uses: actions/upload-artifact@v2
      with:
        name: twisted-artifact-src-dist
        path: ${{ github.workspace }}/dist/*
        if-no-files-found: error

  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-20.04, macos-10.15, windows-2019]
          python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: ./.github/actions/display-python-info

    - name: Get pip cache dir
      id: pip-cache
      run: |
        python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"

    - uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
            ${{ runner.os }}-pip-

    - uses: ./.github/actions/wheels

    - uses: actions/upload-artifact@v2
      with:
        name: twisted-artifact-${{ matrix.os }}-${{ matrix.python-version }}
        path: ${{ github.workspace }}/dist/*.whl
        if-no-files-found: error

  pypi-upload-wheels:
    needs: build-wheels
    runs-on: ubuntu-20.04
    strategy:
      matrix:
          os: [ubuntu-20.04, macos-10.15, windows-2019]
          python-version: [3.5, 3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: twisted-artifact-${{ matrix.os }}-${{ matrix.python-version }}
        path: dist

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: dist

    #- name: Publish package to PyPI
    #  if: startsWith(github.ref, 'refs/tags') && github.event_name == 'release'
    #  uses: pypa/gh-action-pypi-publish@v1.4.1
    #  with:
    #    user: __token__
    #    password: ${{ secrets.PYPI_UPLOAD_TOKEN }}
    #    verbose: true

    - name: Publish package to Test PyPI
      if: startsWith(github.ref, 'refs/tags') && github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@v1.4.1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_UPLOAD_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        verbose: true

  pypi-upload-src-dist:
    needs: build-src-dist
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [ubuntu-20.04]
          python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: twisted-artifact-src-dist
        path: dist

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: dist

    #- name: Publish package to PyPI
    #  if: startsWith(github.ref, 'refs/tags') && github.event_name == 'release'
    #  uses: pypa/gh-action-pypi-publish@v1.4.1
    #  with:
    #    user: __token__
    #    password: ${{ secrets.PYPI_UPLOAD_TOKEN  }}
    #    verbose: true

    - name: Publish package to Test PyPI
      if: startsWith(github.ref, 'refs/tags') && github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@v1.4.1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_UPLOAD_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        verbose: true

